### ISSUE TITLE
YamlのEntity設定の中にMappingが間違えてます（RelatedProduct.dcm.yml） 

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/related-product-plugin#31]
ec-cube 3.0.12
プラグイン： RelatedProduct 0.0.2

問題：YamlのEntity設定の中にMappingが間違えてます
ファイル：
　app/Plugin/RelatedProduct/Resource/doctrine/Plugin.RelatedProduct.Entity.RelatedProduct.dcm.yml

対応方法：
行目：17~
```yaml
    manyToOne:
        Product:
            targetEntity: Eccube\Entity\Product
            inversedBy: RelatedProducts
            joinColumn:
                name: product_id
                referencedColumnName: product_id
        ChildProduct:
            targetEntity: Eccube\Entity\Product
            inversedBy: RelatedChildProducts
            joinColumn:
                name: child_product_id
                referencedColumnName: product_id
    lifecycleCallbacks: {  }
```
↓
```yaml
    manyToOne:
        Product:
            targetEntity: Eccube\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: product_id
        ChildProduct:
            targetEntity: Eccube\Entity\Product
            joinColumn:
                name: child_product_id
                referencedColumnName: product_id
    lifecycleCallbacks: {  }
```
